version:  '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    image:  postgres
    container_name: bloggercontainer
    restart:  always
    environment:
        POSTGRES_DB:  ${DB_NAME}
        POSTGRES_USER:  ${DB_USERNAME}
        POSTGRES_PASSWORD:  ${DB_PASSWORD}
    ports:
      - "5432:5432"

    networks:
      - mynetwork
  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

    networks:
      - mynetwork
  web:
    build: .

    ports:
      - 8000:8000